config { type: "assertion", dependencies: ["huggingface_silver"] }

SELECT source_id
FROM `project-90394262-994e-4667-90d.mrr_silver.huggingface_model_releases`
WHERE bronze_run_id = "${dataform.projectConfig.vars.run_id}"
GROUP BY source_id HAVING COUNT(*) > 1
UNION ALL
SELECT source_id
FROM `project-90394262-994e-4667-90d.mrr_silver.arxiv_paper_submissions`
WHERE bronze_run_id = "${dataform.projectConfig.vars.run_id}"
GROUP BY source_id HAVING COUNT(*) > 1
